[build]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/footballProxy/:splat"
  status = 200

[[redirects]]
  from = "/api/resolve-link"
  to = "/.netlify/functions/resolve-link"
  status = 200